spring.application.name=athlete-analytics

# PostgreSQL Connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate Settings (The Architect)
# "update" tells Hibernate to automatically create our tables when the server starts
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Configuration
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}
application.security.jwt.expiration=${APPLICATION_SECURITY_JWT_EXPIRATION:86400000} 
# (86400000 ms = 24 hours. This means the token will be valid for 24 hours before it expires.)

# Swagger/OpenAPI Configuration
# Tells Swagger to sort the Controller sections alphabetically
springdoc.swagger-ui.tags-sorter=alpha
# Tells Swagger to sort the endpoints inside each controller logically (e.g., DELETE, GET, POST, PUT)
springdoc.swagger-ui.operations-sorter=method

