spring.application.name=athlete-analytics

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/athlete_db
spring.datasource.username=postgres
spring.datasource.password=kb9gb11cr7

# Hibernate Settings (The Architect)
# "update" tells Hibernate to automatically create our tables when the server starts
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000 
# (86400000 ms = 24 hours. This means the token will be valid for 24 hours before it expires.)

# Swagger/OpenAPI Configuration
# Tells Swagger to sort the Controller sections alphabetically
springdoc.swagger-ui.tags-sorter=alpha
# Tells Swagger to sort the endpoints inside each controller logically (e.g., DELETE, GET, POST, PUT)
springdoc.swagger-ui.operations-sorter=method

